# Generated by Django 3.2.7 on 2021-09-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210919_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='state',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=8),
        ),
    ]
