# Generated by Django 3.2.7 on 2021-09-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_category_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_crea', models.DateTimeField(auto_now_add=True)),
                ('date_updat', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_birth', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
    ]
