# Generated by Django 3.2.7 on 2021-09-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_crea', models.DateTimeField(auto_now_add=True)),
                ('date_updat', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(default=1, help_text=' en dólares')),
                ('weight', models.PositiveIntegerField(help_text=' en libras')),
                ('type', models.CharField(choices=[('Virtual', 'Virtual'), ('Físico', 'Físico')], default='Físico', max_length=7)),
                ('url_download', models.URLField(default=None)),
            ],
            options={
                'verbose_name_plural': 'Books',
            },
        ),
    ]
