# Generated by Django 3.2.7 on 2021-09-22 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_book'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('name', 'type')},
        ),
    ]
