# Generated by Django 3.2.7 on 2021-09-22 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_book_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progenitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_crea', models.DateTimeField(auto_now_add=True)),
                ('date_updat', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('father', models.CharField(max_length=50)),
                ('mother', models.CharField(max_length=50)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.person')),
            ],
            options={
                'verbose_name_plural': 'Progenitors',
            },
        ),
    ]
