# Generated by Django 3.2.7 on 2021-09-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20210925_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewFatherSon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idfather', models.IntegerField()),
                ('namefather', models.CharField(max_length=50)),
                ('idson', models.IntegerField()),
                ('nameson', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'view_fatherson',
                'managed': False,
            },
        ),
    ]
