# Generated by Django 3.2.7 on 2021-09-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_viewfatherson'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'new_name',
            },
        ),
    ]
