# Generated by Django 3.2.7 on 2021-10-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_publication_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
